# Generated by Django 5.1.15 on 2026-08-16 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='erp.orgunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.orgunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcmEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete')], max_length=16)),
                ('allow', models.BooleanField(default=True, help_text='True grants the permission; False explicitly revokes it.')),
                ('keycloak_scope', models.CharField(blank=True, default='', help_text='The Keycloak client scope this entry mirrors, if any.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.ForeignKey(help_text='The resource kind: an app model (e.g. erp.invoice).', on_delete=django.db.models.deletion.CASCADE, related_name='acm_entries', to='contenttypes.contenttype')),
                ('subject', models.ForeignKey(help_text='Django group (position or Keycloak-mapped role).', on_delete=django.db.models.deletion.CASCADE, related_name='acm_entries', to='auth.group')),
            ],
            options={
                'db_table': 'erp_acm_entry',
                'ordering': ['subject', 'object_type', 'action'],
                'unique_together': {('subject', 'object_type', 'object_id', 'action')},
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.group')),
                ('kind', models.CharField(choices=[('department', 'Department'), ('position', 'Position'), ('keycloak_role', 'Keycloak role')], max_length=16)),
                ('keycloak_source', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_groups', to='erp.orgunit')),
            ],
            options={
                'db_table': 'erp_group_profile',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'department'), ('scope__isnull', False)), models.Q(('kind', 'position'), ('scope__isnull', True)), models.Q(('kind', 'keycloak_role'), ('scope__isnull', True)), _connector='OR'), name='department_requires_scope')],
            },
        ),
    ]
