# Generated by Django 5.1.15 on 2026-08-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmentry',
            options={'ordering': ['subject', 'object_type', 'action'], 'permissions': [('view_acm', 'Can view the access control matrix')]},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_invoices', 'Can view invoices across all org units')]},
        ),
    ]
